services:
  counter:
    image: node:alpine
    working_dir: /counterService
    ports:
      - 3001:3001
    volumes:
      - ./counterService:/counterService
    command: npm run server
    networks:
      - test-network

  main:
    image: node:20.10-alpine
    working_dir: /app
    ports:
      - 80:3025
    volumes:
      - .:/app
    depends_on:
      - counter
    command: >
      sh -c "apk add --no-cache make gcc g++ python3 && npm run server" // пайтон для bcrypt
    networks:
      - test-network

networks:
  test-network:
    external: true
